# Generated by Django 3.2.9 on 2024-01-01 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemails',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentemails',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
