# Generated by Django 3.2.9 on 2024-01-01 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0002_auto_20240101_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemails',
            name='recipient_email',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
